[Paths]
video_dir = Final
client_secrets = C:/bhakthishorts/bhakti-shorts-automation/Murugan/client_secret.json
token_file = C:/bhakthishorts/bhakti-shorts-automation/Murugan/murugan_token.json

[YouTube]
# Replace with your actual YouTube playlist ID (e.g., PLxxxxxxxxxxxxxxxx)
playlist_id = PL-pNFVmWiWZLjjpRHIop8G_Kb_mJC8a96
category_id = 22
privacy_status = public
# Ensure #Shorts is included in the description for algorithmic discovery
common_hashtags = #முருகன் #Murugan #Shorts #Bhakti #Tamil

[Social]
instagram_url = https://www.instagram.com/vigneshbaskaran1?igsh=N2cxOTY0dGJlNGx0
support_url = https://www.youtube.com/channel/UCZcyzGOG0qFhVBlemfhs_Sw
ig_hashtags = #Murugan #Bhakti #TamilDevotion #TempleShorts